### ISSUE TITLE
Redmi Note 11S (fleur) source codes

### ISSUE THREAD

**Issue by SamadKhafi** [MiCode/Xiaomi_Kernel_OpenSource#2627]
Please release Redmi Note 11S 4G / Poco M4 Pro 4G (fleur) kernel source codes.

**Comment by MUSAdotEXE** [comment]
Please release kernal source for poco m4 pro 4g device.

**Comment by Dhiraj3ddd** [comment]
Dear Xiaomi please release kernel sources of Redmi note 11s AKA Poco M4 PRO 4g codename "fleur" .It's already been one whole YEAR since the phone is launched.This is against the spirit of OPENSOURCE Community. Do release the updated kernel sources of the "fleur" it's been a very long OVERDUE already.

**Comment by BloxetPL** [comment]
ITS PUBLISHED!
