### ISSUE TITLE
Xiaomi Redmi 5 Plus (vince)

### ISSUE THREAD

**Issue by obsvg216** [MiCode/Xiaomi_Kernel_OpenSource#861]
Please post the kernel source code. We are all very much waiting for this.

**Comment by 0312birdzhang** [comment]
+1

**Comment by mdeejay** [comment]
Xiaomi WTF? Where source codes for vince?

**Comment by mohancm** [comment]
@mdeejay you got Vince?

**Comment by mdeejay** [comment]
yup

**Comment by mdeejay** [comment]
bombing Xiaomi twitter right now.

**Comment by mohancm** [comment]
Lol

**Comment by Yhd12138-zz** [comment]
Vince 😍

**Comment by mdeejay** [comment]
And what you waiting, Xiaomi?
Stop violating GPL! Release all opensource for vince!

**Comment by luk1337** [comment]
cry more, it's definitely going to help.

**Comment by Blacksuan19** [comment]
yo bitch ass niggas released the source for whyred and not vince wtf
commit to motherfucking GPL dammit

**Comment by InZaneDanii** [comment]
Please Release the Kernel Source for Redmi 5 Plusby modifying and distributing GPL software, this has to comply with the GPL terms, in this case GPLv2. And therefore this I kindly request you release kernel sources otherwise this would be copyright infringement.According to the GPL v2 license terms all modifications made to the Linux kernel must be released to the public. Please follow the terms of the license you are using. Thank you

**Comment by ghost** [comment]
Whats wrong with you Xiaomi??! You release source code for whyred, but for Vince cant??? WTF!!

**Comment by AakashPandey** [comment]
Release the source your 9.5 is bloated with spywares, we need to jump to aosp / lineage

**Comment by obsvg216** [comment]
Closed

**Comment by thenanobel** [comment]
@obsvg216 Why have you closed the issue? Have them released the source code?

**Comment by obsvg216** [comment]
@thenanobel yes, in tiffany-n-oss branch
